### ISSUE TITLE
打包dist问题

### ISSUE THREAD

**Issue by xiayesuifeng** [zhiyicx/plus-component-h5#101]
就不能打包下dist？
![image](https://user-images.githubusercontent.com/8142265/28515628-f4e50e90-7023-11e7-820f-636dce712365.png)
一堆打包问题
而且yarn disk还要用trash dist/*
这文件夹本来就不存在还报错

**Comment by boxshadow** [comment]
你的包都没有安装吧

**Comment by medz** [comment]
You need run:

```shell
yarn install
```

Or

```shell
npm install
```

**Comment by 1377195627** [comment]
![_ _20170727141444](https://user-images.githubusercontent.com/8142265/28656842-c01edf68-7269-11e7-943f-7d4476d8c4e5.png)
昨天已经安装好了，但是注册有问题，短信发不出去，阿里大于已经配置

![_ _20170727141444](https://user-images.githubusercontent.com/8142265/28656842-c01edf68-7269-11e7-943f-7d4476d8c4e5.png)
![_ _20170727141520](https://user-images.githubusercontent.com/8142265/28656853-d0abc3dc-7269-11e7-8694-8eeb2213f642.png)

![_ _20170727141543](https://user-images.githubusercontent.com/8142265/28656855-d47f4d6c-7269-11e7-9817-1ad30fe44f6c.png)

**Comment by boxshadow** [comment]
可否提交一下response @1377195627
