### ISSUE TITLE
【消息】用户是默认头像时未显示头像占位图

### ISSUE THREAD

**Issue by maanrry** [zhiyicx/plus-component-h5#114]
## 描述
用户是默认头像时未显示头像占位图

**Comment by boxshadow** [comment]
@maanrry 提供页面截图

**Comment by maanrry** [comment]
![image](https://user-images.githubusercontent.com/30249193/33362015-680678b8-d515-11e7-9031-ba47bebc407c.png)
![image](https://user-images.githubusercontent.com/30249193/33362024-720a2f6c-d515-11e7-8baa-c2968b40cd5c.png)
