### ISSUE TITLE
【发现--资讯--搜索】输入关键字点击搜索后点击文章进入文章详情页，文章详情页缺”返回“按钮

### ISSUE THREAD

**Issue by maanrry** [zhiyicx/plus-component-h5#166]
## 描述
进入发现--资讯，点击搜索进入搜索页面，输入关键字点击搜索，选择与关键字相关的文章进入该文章详情页，详情页缺”返回“键
## 配图
![image](https://user-images.githubusercontent.com/30249193/32043353-20856d68-ba6d-11e7-9a2b-7c8675185da4.png)

**Comment by huhaophp** [comment]
已修复
