### ISSUE TITLE
【发现-资讯-资讯详情】删除自己发布的评论弹出“删除动态”

### ISSUE THREAD

**Issue by peicaichi** [zhiyicx/plus-component-h5#274]
## 配图
![image](https://user-images.githubusercontent.com/22809873/33248850-3d949164-d362-11e7-8cc8-25b761004def.png)

**Comment by Jungle68** [comment]
1.目前 ios safiri 浏览器无法弹起键盘
2.评论后没有立即显示在列表里面；
3.无法回复他人评论；
4.无法删除自己的评论；
5.也无法长安举报他人评论；

**Comment by mutoe** [comment]
除举报功能外均已修复
