### ISSUE TITLE
【发现--圈子】列表上时间显示不对

### ISSUE THREAD

**Issue by maanrry** [zhiyicx/plus-component-h5#300]
##配图
![image](https://user-images.githubusercontent.com/30249193/33254452-d221849c-d383-11e7-9c4c-2a046e83e47f.png)
## 用例
![image](https://user-images.githubusercontent.com/30249193/33254473-dfd64032-d383-11e7-9655-2ed69f233aea.png)

**Comment by mutoe** [comment]
refer #204
