### ISSUE TITLE
安装 composer依赖html5移动版扩展出错

### ISSUE THREAD

**Issue by yangtaocheng** [zhiyicx/plus-component-h5#337]
[root@JD thinksns-plus]# composer require/zhiyicx/plus-component-web
Do not run Composer as root/super user! See https://getcomposer.org/root for details

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "require/zhiyicx/plus-component-web" is not defined.

**Comment by yangtaocheng** [comment]
[InvalidArgumentException]                                                                                                                                                                  
  Could not find a matching version of package /zhiyicx/plus-component-h5. Check the package spelling, your version constraint and that the package is available in a stability which matche  
  s your minimum-stability (stable).

**Comment by yangtaocheng** [comment]
[InvalidArgumentException]                                                                                                                                                                  
  Could not find a matching version of package /zhiyicx/plus-component-web. Check the package spelling, your version constraint and that the package is available in a stability which match  
  es your minimum-stability (stable).

**Comment by yangtaocheng** [comment]
找不到包的匹配版本

**Comment by medz** [comment]
你输入错了
```shell
composer require zhiyic.plus-component-h5
```
