### ISSUE TITLE
如何禁用eslint？

### ISSUE THREAD

**Issue by godblessu** [zhiyicx/plus-component-h5#340]
如何禁用eslint？

**Comment by JsonLeex** [comment]
修改配置文件`./vue.config.js` 
```javascript
{
    ...
    // lintOnSave: true
    lintOnSave: false
    ...
}
 ```
![image](https://user-images.githubusercontent.com/25883665/37763656-a9ad479a-2dfa-11e8-85bc-dc0fe9990525.png)

**Comment by godblessu** [comment]
谢谢
