### ISSUE TITLE
获取文件 报跨域错误 其他 api 接口 正常 

### ISSUE THREAD

**Issue by zanjs** [zhiyicx/plus-component-h5#348]
Failed to load http://127.0.0.1:8000/api/v2/files/4?q=40&json=1: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:5000' is therefore not allowed access.

发起  `get` 请求 请求发起了 `OPTIONS` 没有 

![_20180508172808](https://user-images.githubusercontent.com/12947276/39749443-3dcf6d4a-52e5-11e8-95cf-52e4dd28bd8c.png)

**Comment by boxshadow** [comment]
此组件已经采用client+api的分离部署方式, 需要在服务端管理后台设置跨域权限

**Comment by zanjs** [comment]
@boxshadow  嗯 明白 设置过了 ， 其他 api 都正常请求 就这个接口不可以

**Comment by boxshadow** [comment]
如是是vue-cli 用开发模式的话是不会出现跨域的, 除非是 larave的.env文件里 APP_URL和你设置的 127.0.0.1:8000不一样

**Comment by zanjs** [comment]
@boxshadow 开发模式没问题， 我现在是 生成环境遇到问题 ，

##  client 
```
VUE_APP_API_HOST=http://127.0.0.1:8000
```

## api

```
APP_URL=http://127.0.0.1:8000
DATA_LIMIT=15

CORS_LARAVEL_ROUTE_GROUP_MODE=true
CORS_LARAVEL_ALLOW_ROUTE_PERFIX="*"
CORS_ALLOW_CREDENTIAILS=false
CORS_ACCESS_CONTROL_MAX_AGE=600
```

设置应该没问题 ，一样的 。

## 获取文件 `json` 接口

```
GET /files/:file
```

直接 get 或者这个接口没问题，

问题是  客户端在请求 api 的时候 先要发送  `OPTIONS` 确认后在 发起 ` get `请求, 

错误就在 发起   `OPTIONS` 的 时候  会跨域错

![Uploading 微信截图_20180508175850.png…]()


其他 `api` 发起  `OPTIONS`  正常

**Comment by JsonLeex** [comment]
这个问题并不是跨域引起的, 你可以到 "./src/api/api.js" 46行, 输出错误日志

**Comment by zanjs** [comment]
@JsonLeex  

Error: Network Error
    at FtD3.t.exports (createError.js:16)
    at XMLHttpRequest.h.onerror (xhr.js:87)

**Comment by zanjs** [comment]
## api.php

```
tap($api->any('/files/{fileWith}', API2\FilesController::class.'@show'), function ($route) {
        $route->setAction(array_merge($route->getAction(), [
            // 'middleware' => 'cors-should',
            'middleware' => 'bindings',
        ]));
    });
```

修改为 

```
$api->any('files/{fileWith}', API2\FilesController::class.'@show');
```

**Comment by godblessu** [comment]
我之前也遇到过这个问题， 也是把路由那行注释掉就好了， 不明白开发者为什么还要绑定这个中间件

**Comment by medz** [comment]
@zanjs @godblessu 已修复，详见👉 https://github.com/slimkit/thinksns-plus/commit/ffc068308be14eb72cb9732085901580390267e6
