### ISSUE TITLE
【注册】注册时输入已经存在的用户名，提示显示了两行

### ISSUE THREAD

**Issue by LMTcancan** [zhiyicx/plus-component-h5#351]
## 机型
iPhone 7
浏览器：Safari

## 描述
注册时输入已经存在的用户名，提示显示了两行，且提示成功后注册按钮一直处于加载中，无法再点击

## 配图
<img width="269" alt="d5306dbd-c6dd-44df-a866-f2fbe64a7b54" src="https://user-images.githubusercontent.com/25689097/39848010-2e3348cc-5437-11e8-86af-9ce9b17bb31a.png">

**Comment by mutoe** [comment]
fixed via https://github.com/zhiyicx/plus-component-h5/commit/ef6c00fb6ae1d38a07e5397fad769dda77fc17ae

**Comment by mutoe** [comment]
fixed via 5eb265b8e8464e364f1d40c2b72001770efa0c6a
