### ISSUE TITLE
【首页-申请动态置顶】多处错误

### ISSUE THREAD

**Issue by maanrry** [zhiyicx/plus-component-h5#364]
## 配图
一、下图两处问题：
1.与设计不符，没有显示当前申请置顶的最高金额和用户自己的积分余额
2.无法删除已输入的金额
![image](https://user-images.githubusercontent.com/30249193/39849210-c3c9f79a-543d-11e8-8af4-e55956e5e0b1.png)
- 设计图
![image](https://user-images.githubusercontent.com/30249193/39849288-29ce68b4-543e-11e8-9731-1f697f543d7f.png)
二、输入置顶金额为0时，总金额没有显示（现在需求修改成输入0也可以申请成功）
![image](https://user-images.githubusercontent.com/30249193/39849331-5d72ee4c-543e-11e8-9261-8d30eb10ce72.png)

**Comment by maanrry** [comment]
同时“D”修改成“天”

**Comment by Jungle68** [comment]
需求变动： 307. [H5, IOS, Android] 申请置顶页面，1d/5d/10d 改成1天/5天/10天； 置顶金额 改成 每日支付，后面输入框提示文字改成 输入金额； 总金额 改成 共需支付， 后面的提示文本置空；下面的描述模版“最近置顶平均100积分/天，可用积分200”，平均值以服务端给的为准，如果服务端给的值小于1，则修正为100。 如果申请后是自己审核的， 按钮改成 “确认置顶”。

**Comment by JsonLeex** [comment]
暂时缺少”平均值 显示“。
