### ISSUE TITLE
【首页-动态详情】顶部缺少关注图标

### ISSUE THREAD

**Issue by maanrry** [zhiyicx/plus-component-h5#372]
## 机型
- [x] vivox7
- [x] vivo自带浏览器
## 配图
未关注的用户从动态列表进入动态详情页，底部缺少“关注”图标
![image](https://user-images.githubusercontent.com/30249193/39849933-658e76f2-5441-11e8-956f-7d4759092d6a.png)
Android端：
![image](https://user-images.githubusercontent.com/30249193/39849938-6db6631c-5441-11e8-8bc3-c6bae604ef15.png)

**Comment by JsonLeex** [comment]
暂不处理 @
