### ISSUE TITLE
【首页-动态】查看付费的图片在列表上付费之后进入动态详情再返回到动态列表上图片仍然是高斯模糊的

### ISSUE THREAD

**Issue by maanrry** [zhiyicx/plus-component-h5#374]
## 机型
- [x] vivox7
- [x] vivo自带浏览器
## 描述
查看付费的图片在列表上付费之后进入动态详情再返回到动态列表上图片仍然是高斯模糊的
## 配图
![image](https://user-images.githubusercontent.com/30249193/39850636-088097a2-5445-11e8-8c38-5d56647e2131.png)

**Comment by maanrry** [comment]
在最新或者在热门查看需要付费的图片之后进入热门或最新仍然是高斯模糊

**Comment by mutoe** [comment]
refer to #450
