### ISSUE TITLE
【发布-图片】设置付费图片的弹窗，自定义金额布局错误

### ISSUE THREAD

**Issue by LMTcancan** [zhiyicx/plus-component-h5#385]
## 机型
iPhone 7
浏览器：Safari

## 描述
1. 自定义金额和积分输入栏没有对齐
2. 在PC端的网页查看会出现多余按钮，移动端没有

## 配图
<img width="279" alt="1a587383-4260-493d-8519-a4b0823e5af5" src="https://user-images.githubusercontent.com/25689097/39855642-4748376e-545f-11e8-99db-cc3aa479b640.png">

## 预期
1. 自定义金额和积分输入栏对齐在一栏显示
2. 去掉PC端的显示

**Comment by Jungle68** [comment]
safari 不处理
