### ISSUE TITLE
【发布-图片】先开启图片付费并设置金额后，再关闭图片付费发布，在动态列表图片模糊显示

### ISSUE THREAD

**Issue by LMTcancan** [zhiyicx/plus-component-h5#404]
## 机型
iPhone 7
浏览器：Safari
## 描述
先开启图片付费并设置金额后，再关闭图片付费发布，在动态列表图片模糊显示，点击后还需要付费才能查看

## 预期
关闭了付费后发布的图片可以直接显示，不需要模糊

**Comment by Jungle68** [comment]
当图片设置的是下载收费的时候，h5也需要付费查看
