### ISSUE TITLE
【我的-个人资料】多个问题

### ISSUE THREAD

**Issue by maanrry** [zhiyicx/plus-component-h5#414]
## 机型
- [x] vivox7
- [x] vivo自带浏览器
## 描述
1.修改资料之后没有提示
2.个人简介超过50字之后还能继续输入最后提示不能超过50字，修改成输入50字之后不能继续输入
3.进入个人资料之后点击“个人简介”弹出键盘之后，简介内容被遮挡，需要修改成键盘弹出来之后内容被顶上去
问题2配图
![image](https://user-images.githubusercontent.com/30249193/39862109-5d5c76d0-5475-11e8-8f80-b62d93d3810e.png)
问题3配图
![image](https://user-images.githubusercontent.com/30249193/39862121-66a7aa70-5475-11e8-9eae-f4fdde98baf0.png)

**Comment by LMTcancan** [comment]
iPhone 7
浏览器：Safari

1. 删除简介内容时，删除一个字后，光标跳到开头
2. 简介只有到达33个字时，应该才显示字数统计。目前始终显示了字数统计
3. 修改个人资料并点击“完成”按钮后，没有回到上一页
