### ISSUE TITLE
【游客模式】游客进入排行榜列表点击关注，提示语错误且没有跳转到游客登录页面

### ISSUE THREAD

**Issue by LMTcancan** [zhiyicx/plus-component-h5#415]
## 机型
iPhone 7
浏览器：Safari
## 描述
游客进入排行榜列表点击关注，提示语错误且没有跳转到游客登录页面

## 配图
<img width="260" alt="4a6606ca-640e-4f36-9b45-b1390cbb0160" src="https://user-images.githubusercontent.com/25689097/39862262-d4ae074e-5475-11e8-8e1e-d39918e8169a.png">

**Comment by maanrry** [comment]
游客模式点击用户头像仍然还能进入个人主页
