### ISSUE TITLE
【我的-收藏】进入收藏页面出现两个“加载中”

### ISSUE THREAD

**Issue by maanrry** [zhiyicx/plus-component-h5#431]
## 机型
- [x] vivox7
- [x] vivo自带浏览器

## 配图
![image](https://user-images.githubusercontent.com/30249193/39908934-02b96e6e-5523-11e8-92cd-8636cd7a8e00.png)

**Comment by maanrry** [comment]
进入视频动态详情页返回收藏列表页存在这个问题

**Comment by mutoe** [comment]
这边没有复现，是否已经修复了？ 🤔
