### ISSUE TITLE
如果安装这个动态应用？

### ISSUE THREAD

**Issue by 121753961** [zhiyicx/plus-component-h5#98]
已经按照说明步骤：
composer require zhiyicx/plus-component-web
php artisan package:handle h5 publish
执行完这两个步骤了，要怎么访问页面，是不是还有其他的步骤，麻烦整个详情的说明文档吧。辛苦了

**Comment by 121753961** [comment]
@medz 
安装和发布都没有报错
![image](https://user-images.githubusercontent.com/12001672/27952227-243b8f26-633a-11e7-9078-e0d0fa98f20f.png)

![image](https://user-images.githubusercontent.com/12001672/27952164-f08f9a14-6339-11e7-94b0-259ea8dee9a0.png)

**Comment by medz** [comment]
```shell
cd vendor/zhiyicx/plus-component-web && yarn build && cd ../../../ && php artisan package:handle h5 publish
```
目前还在开发状态，没有打包 dist。

**Comment by 121753961** [comment]
@medz 
没有 build 这个构建

![image](https://user-images.githubusercontent.com/12001672/27982032-a6e112f8-63ca-11e7-9c7f-2e5d259dfbea.png)

**Comment by boxshadow** [comment]
@121753961 yarn dist 即可
